#!/bin/bash

# usage, run test suite. 
# ./test -> run entire suite
# ./test `mark` -> runs tests marked with @mark. See pytest.ini in project root for custom marks
# ./test verbose -> runs entire suite while printing output from failed tests to stdout
# ./test verbose `mark` -> verbose but for tests marked with @mark


if [[ $1 == "verbose" ]]
then
    if [[ $# == 1 ]]
    then
        python -m pytest -s $2
        exit 0
    fi

    if [[ $# == 2 ]]
    then
        python -m pytest -s -m $2
        exit 0
    fi
else 
if [[ $# == 0 ]]
    then
	python -m pytest tests/
        exit 0
    fi

    if [[ $# == 1 ]]
    then
        python -m pytest -m $1
        exit 0
    fi
fi
